### ISSUE TITLE
Error add font thai 

### ISSUE THREAD

**Issue by mustakeam** [geekcom/phpjasper#342]
How to fix 
Fatal error: Uncaught PHPJasper\Exception\ErrorCommandExecutable: Exception in thread "main" net.sf.jasperreports.engine.util.JRFontNotFoundException: Font "THSarabunNew" is not available to the JVM. See the Javadoc for more details. at net.sf.jasperreports.engine.fonts.FontUtil.checkAwtFont(FontUtil.java:604) at net.sf.jasperreports.engine.fill.SimpleTextLineWrapper.loadFont(SimpleTextLineWrapper.java:384) at net.sf.jasperreports.engine.fill.SimpleTextLineWrapper.getGeneralFontInfo(SimpleTextLineWrapper.java:354) at net.sf.jasperreports.engine.fill.SimpleTextLineWrapper.createFontInfo(SimpleTextLineWrapper.java:294) at net.sf.jasperreports.engine.fill.SimpleTextLineWrapper.start(SimpleTextLineWrapper.java:256) at net.sf.jasperreports.engine.fill.TextMeasurer.measure(TextMeasurer.java:543) at net.sf.jasperreports.engine.fill.JRFillTextElement.chopTextElement(JRFillTextElement.java:665) at net.sf.jasperreports.engine.fill.JRFillStaticText.prepare(JRFillStaticText.java:179) at net.sf.jasperreports in C:\xampp\htdocs\phpjasper\src\PHPJasper.php on line 251
![image](https://github.com/PHPJasper/phpjasper/assets/59229011/9a3ff9bf-1021-428a-ac4e-315d4099bb78)
![image](https://github.com/PHPJasper/phpjasper/assets/59229011/1d65cd2f-363c-490c-beb7-6351bdb47b62)

**Comment by polppol** [comment]
I think you should include jar of Thai font as a report "resources"
for jasperstarter You can do it like "jasperstarter pr myreport.jasper -f view -r myresources.jar"
but not sure how to do it with PHPJasper
I still finding too, 

ps. i saw this https://github.com/PHPJasper/phpjasper/issues/344 
but no one answer yet of how to add external resources with PHPJasper

**Comment by SWK-Yoyo** [comment]
I have the smae problem. I fix it by add .ttf font into Java\jreX.X.X_XXX\lib\fonts folder and add pdfFontName into .jrxml file and it work (but i don't know how it work)

**Comment by ThantsinKS** [comment]
did you solve this error?

**Comment by ThantsinKS** [comment]
> I have the smae problem. I fix it by add .ttf font into Java\jreX.X.X_XXX\lib\fonts folder and add pdfFontName into .jrxml file and it work (but i don't know how it work)

could you explain one more again?

**Comment by SWK-Yoyo** [comment]
My font in file .jrxml look like this
`<font fontName="Angsana New" size="14" pdfFontName="./fonts/ANGSAU.TTF" pdfEncoding="Identity-H"/>
`
1. I add font in Java folder  `C:\Program Files\Java\jreX.X.X_XXX\lib\fonts` for `fontName` format block
2. Add path font you want to use in `pdfFontName`
3. Set `pdfEncoding="Identity-H"` for encode font

**Comment by ThantsinKS** [comment]
this is my .jrxml 
```
<textElement verticalAlignment="Middle">
					<!-- <font fontName="Noto Sans JP" pdfFontName="storage/fonts/NotoSansJP-Regular.ttf" isPdfEmbedded="true"/> -->
					<font fontName="Noto Sans JP" pdfFontName="var/www/html/jasper/fonts/NotoSansJP-Regular.ttf" pdfEncoding="Identity-H" />
				</textElement>
```
and i add font in this path beacuase i am using docker 

```
COPY fonts/* /jasper/fonts/

ENV CLASSPATH=$CLASSPATH:/jasper/fonts
```
 and i have .ttf file

![Image](https://github.com/user-attachments/assets/17ccc29c-72cd-45ab-9675-a4e56bc7e831)

![Image](https://github.com/user-attachments/assets/21c34569-5bbd-4bf9-be39-daefbe328960) 
and this is my laravel code, what is wrong with mine  could you please show me how should i do

**Comment by ThantsinKS** [comment]
> My font in file .jrxml look like this `<font fontName="Angsana New" size="14" pdfFontName="./fonts/ANGSAU.TTF" pdfEncoding="Identity-H"/> `
> 
> 1. I add font in Java folder  `C:\Program Files\Java\jreX.X.X_XXX\lib\fonts` for `fontName` format block
> 2. Add path font you want to use in `pdfFontName`
> 3. Set `pdfEncoding="Identity-H"` for encode font


this is my .jrxml 
```
<textElement verticalAlignment="Middle">
					<!-- <font fontName="Noto Sans JP" pdfFontName="storage/fonts/NotoSansJP-Regular.ttf" isPdfEmbedded="true"/> -->
					<font fontName="Noto Sans JP" pdfFontName="var/www/html/jasper/fonts/NotoSansJP-Regular.ttf" pdfEncoding="Identity-H" />
				</textElement>
```
and i add font in this path beacuase i am using docker 

```
COPY fonts/* /jasper/fonts/

ENV CLASSPATH=$CLASSPATH:/jasper/fonts
```
 and i have .ttf file

![Image](https://github.com/user-attachments/assets/17ccc29c-72cd-45ab-9675-a4e56bc7e831)

![Image](https://github.com/user-attachments/assets/21c34569-5bbd-4bf9-be39-daefbe328960) 
and this is my laravel code, what is wrong with mine  could you please show me how should i do

**Comment by SWK-Yoyo** [comment]
I don't know docker and this problem so much but can you try this for me pls
1.  remove `fontName="Noto Sans JP"` and run it
2. If it work but format character not work  can you direct set font in `jre\lib\fonts`
